In [30]:
import os
import subprocess
import pickle
import pandas as pd
import numpy as np
from IPython.display import display
from utils_feature_engineering import *

# Load application train data

In [31]:
# load train data
path = r'D:\NEU\Năm 3\DATA PREP\PROJECT_DATAPREP\GITHUB REPO\dataset\dseb63_final_project_DP_dataset\\'
application_train = pd.read_csv(path + 'dseb63_' + 'application_train.csv')
application_train.drop(columns='Unnamed: 0',inplace=True)

# get X_train label
application_train_filtered = application_train[['SK_ID_CURR','TARGET']]

In [32]:
# preprocessing/features_fullfill/train_test_num_fullfill_ext_ridge_final_imputer_0.pkl.bz2 preprocessing/features_fullfill/train_test_cat_fullfill_final_ridge_imputer_0.pkl.bz2#

# Combine Features

In [33]:
# check features folders
os.listdir('features')

['bureau.pkl.bz2',
 'bureau_balance.pkl.bz2',
 'bureau_merged_balance.pkl.bz2',
 'credit_card_balance.pkl.bz2',
 'df_features_label.csv.bz2',
 'df_features_label.pkl.bz2',
 'df_features_label_fullfill.pkl.bz2',
 'df_features_label_fullfill_ext_1989_taylor_version.pkl.bz2',
 'df_features_label_fullfill_ext_cnt.pkl.bz2',
 'df_features_label_fullfill_ext_imputer.pkl.bz2',
 'df_features_label_fullfill_ext_imputer_0.pkl.bz2',
 'df_features_label_fullfill_ext_imputer_mode.pkl.bz2',
 'df_features_label_fullfill_ext_lasso.pkl.bz2',
 'df_features_label_fullfill_ext_lr.pkl.bz2',
 'df_features_label_fullfill_ext_lr_verion2.pkl.bz2',
 'df_features_label_fullfill_ext_lr_verion2_test.pkl.bz2',
 'df_features_label_fullfill_ext_ridge.pkl.bz2',
 'df_features_label_fullfill_ext_tune.pkl.bz2',
 'installments_payments.pkl.bz2',
 'mean_encoding_feat_cat.pkl.bz2',
 'pos_cash.pkl.bz2',
 'prev_app.pkl.bz2',
 'TARGET_MEAN_500_Neighbors_training_data.pkl',
 'train_test_cat.pkl.bz2',
 'train_test_cat_fullfill.pkl.bz2',
 'train_test_cat_fullfill_2.pkl.bz2',
 'train_test_cat_fullfill_2_test.pkl.bz2',
 'train_test_cat_fullfill_final.pkl.bz2',
 'train_test_cat_fullfill_final_cnt.pkl.bz2',
 'train_test_cat_fullfill_final_imputer.pkl.bz2',
 'train_test_cat_fullfill_final_imputer_0.pkl.bz2',
 'train_test_cat_fullfill_final_imputer_mode.pkl.bz2',
 'train_test_cat_fullfill_final_lasso_imputer_0.pkl.bz2',
 'train_test_cat_fullfill_final_ridge_imputer_0.pkl.bz2',
 'train_test_cat_fullfill_final_tune.pkl.bz2',
 'train_test_num.pkl.bz2',
 'train_test_num_fullfill.pkl.bz2',
 'train_test_num_fullfill_ext_lasso_final_imputer_0.pkl.bz2',
 'train_test_num_fullfill_ext_lr.pkl.bz2',
 'train_test_num_fullfill_ext_lr_2.pkl.bz2',
 'train_test_num_fullfill_ext_lr_2_test.pkl.bz2',
 'train_test_num_fullfill_ext_lr_final.pkl.bz2',
 'train_test_num_fullfill_ext_lr_final_cnt.pkl.bz2',
 'train_test_num_fullfill_ext_lr_final_imputer.pkl.bz2',
 'train_test_num_fullfill_ext_lr_final_imputer_0.pkl.bz2',
 'train_test_num_fullfill_ext_lr_final_imputer_mode.pkl.bz2',
 'train_test_num_fullfill_ext_lr_final_tune.pkl.bz2',
 'train_test_num_fullfill_ext_ridge_final_imputer_0.pkl.bz2']

In [34]:
# os.listdir('featur')

In [35]:
# specified features set for merging
ls_feat_file = ['bureau_merged_balance.pkl.bz2',
                'credit_card_balance.pkl.bz2',
                'installments_payments.pkl.bz2',
                'pos_cash.pkl.bz2',
                'prev_app.pkl.bz2',
                'train_test_num_fullfill_ext_lr_final_imputer_0.pkl.bz2',
                'train_test_cat_fullfill_final_imputer_0.pkl.bz2']

In [36]:
%%time
# use first features for base joined
feat_path = os.path.join('features', ls_feat_file[0])
df_combined = pd.read_pickle(feat_path, compression='bz2')

# join the remaing features list
for fname in ls_feat_file[1:]:
    feat_path = os.path.join('features', fname)
    df_feat = pd.read_pickle(feat_path, compression='bz2')
    print(fname, df_feat.shape)

    # add table prefix
    tbl_prefix = fname.split('.')[0]
    rename_col = {cname: "{}_{}".format(tbl_prefix, cname) for cname in df_feat.columns if cname != "SK_ID_CURR"}
    df_feat = df_feat.rename(columns = rename_col)

    # merge  
    df_combined = df_combined.merge(df_feat, on = 'SK_ID_CURR', how = 'left')

print("rows, columns", df_combined.shape)
ls_features = [feat for feat in df_combined.columns if feat not in ["SK_ID_CURR"]]
display(df_combined.head())

credit_card_balance.pkl.bz2 (86905, 111)
installments_payments.pkl.bz2 (180733, 35)
pos_cash.pkl.bz2 (289444, 36)
prev_app.pkl.bz2 (291057, 242)

<timed exec>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

train_test_num_fullfill_ext_lr_final_imputer_0.pkl.bz2 (307511, 87)

<timed exec>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

train_test_cat_fullfill_final_imputer_0.pkl.bz2 (307511, 82)
rows, columns (263491, 680)

,SK_ID_CURR,CREDIT_ACTIVE_Closed_mean,CREDIT_ACTIVE_Active_mean,CREDIT_ACTIVE_Active_sum,CREDIT_ACTIVE_Closed_sum,CREDIT_TYPE_Credit_card_mean,CREDIT_TYPE_Credit_card_sum,CREDIT_ACTIVE_Closed_max,CREDIT_TYPE_Consumer_credit_mean,CREDIT_ACTIVE_Active_max,...,train_test_cat_fullfill_final_imputer_0_ORGANIZATION_TYPE_Bank,train_test_cat_fullfill_final_imputer_0_ORGANIZATION_TYPE_Security,train_test_cat_fullfill_final_imputer_0_NAME_EDUCATION_TYPE_Incomplete_higher,train_test_cat_fullfill_final_imputer_0_WALLSMATERIAL_MODE_Monolithic,train_test_cat_fullfill_final_imputer_0_is_EMERGENCYSTATE_MODE,train_test_cat_fullfill_final_imputer_0_NAME_HOUSING_TYPE_Office_apartment,train_test_cat_fullfill_final_imputer_0_ORGANIZATION_TYPE_Agriculture,train_test_cat_fullfill_final_imputer_0_ORGANIZATION_TYPE_Industry__type_9,train_test_cat_fullfill_final_imputer_0_ORGANIZATION_TYPE_Restaurant,train_test_cat_fullfill_final_imputer_0_OCCUPATION_TYPE_Waiters_barmen_staff
0,0,0.000000,1.000000,1,0,0.000000,0,0,1.000000,1,...,0,0,1,0,0,0,0,0,0,0
1,1,0.000000,1.000000,1,0,0.000000,0,0,1.000000,1,...,0,0,0,0,0,0,0,0,0,0
2,2,0.666667,0.333333,2,4,0.000000,0,1,1.000000,1,...,0,0,0,0,0,0,0,0,0,0
3,3,0.571429,0.428571,3,4,0.142857,1,1,0.857143,1,...,0,0,0,0,0,0,0,0,0,0
4,4,0.500000,0.500000,3,3,0.166667,1,1,0.833333,1,...,0,0,0,0,0,0,0,0,0,0

Wall time: 33.6 s

In [37]:
path = r'D:\NEU\Năm 3\DATA PREP\PROJECT_DATAPREP\GITHUB REPO\dataset\dseb63_final_project_DP_dataset\\'
# train
application_train = pd.read_csv(path + 'dseb63_' + 'application_train.csv')
application_train.drop(columns='Unnamed: 0', inplace=True)
# test
application_test = pd.read_csv(path + 'dseb63_' + 'application_test.csv')
application_test.drop(columns='Unnamed: 0', inplace=True)

In [38]:
%%time
if False :
    # xây dựng hàm để lọc ra các feature có auc thấp
    def filter_feat_low_auc(df_label, df_input, threshold = 0.501):
        df_eval = feature_evaluate(df_label, df_input)
        ls_filtered_feat = df_eval[df_eval['auc'] > threshold]['name'].tolist()
        return ls_filtered_feat
    

    ls_filtered_feat = filter_feat_low_auc(application_train_filtered, df_combined, threshold = 0.501)
    df_combined = df_combined[['SK_ID_CURR' + ls_filtered_feat]]
    print('-'*100)
    print("After filtered : {}".format(df_combined.shape))

Wall time: 0 ns

# Join with label

In [39]:
application_tvt = pd.read_pickle("application_tvt_extend.pkl", compression="bz2")
print(application_tvt.shape)
display(application_tvt.head())

(307511, 3)

   SK_ID_CURR  TARGET tvt_code
0      278621       0    train
1      139008       0    train
2      138348       0    train
3       64140       0     test
4      219374       0      val

In [40]:
application_tvt["tvt_code"].value_counts()

train          173558
kaggle_test     61502
test            36902
val             35549
Name: tvt_code, dtype: int64

In [41]:
df_features_labels = application_tvt.merge(df_combined, on = 'SK_ID_CURR', how = 'left')
print(df_features_labels.shape)
df_features_labels.head().T

(307511, 682)

,0,1,2,3,4
SK_ID_CURR,278621,139008,138348,64140,219374
TARGET,0,0,0,0,0
tvt_code,train,train,train,test,val
CREDIT_ACTIVE_Closed_mean,0.75,NaN,1.0,0.666667,0.5
CREDIT_ACTIVE_Active_mean,0.25,NaN,0.0,0.333333,0.5
...,...,...,...,...,...
train_test_cat_fullfill_final_imputer_0_NAME_HOUSING_TYPE_Office_apartment,0.0,NaN,0.0,0.0,0.0
train_test_cat_fullfill_final_imputer_0_ORGANIZATION_TYPE_Agriculture,0.0,NaN,0.0,0.0,0.0
train_test_cat_fullfill_final_imputer_0_ORGANIZATION_TYPE_Industry__type_9,0.0,NaN,0.0,0.0,0.0
train_test_cat_fullfill_final_imputer_0_ORGANIZATION_TYPE_Restaurant,0.0,NaN,0.0,0.0,0.0
train_test_cat_fullfill_final_imputer_0_OCCUPATION_TYPE_Waiters_barmen_staff,0.0,NaN,0.0,0.0,0.0

### Save Features

In [42]:
%%time
# save combined features with label
df_features_labels.to_pickle(os.path.join("features", "df_features_label_fullfill_ext.pkl.bz2"), compression="bz2")
print("Store features completed!")

Store features completed!
Wall time: 1min 42s